### ISSUE TITLE
undefined method `source_index' for Gem:Module

### ISSUE THREAD

**Issue by darrenleeweber** [rweng/pry-rails#95]
```
$  rbenv which ruby
/users/dlweber/.rbenv/versions/2.4.1/bin/ruby
$  rbenv which gem
/users/dlweber/.rbenv/versions/2.4.1/bin/gem
$  gem --version
2.6.11
$  rbenv which bundle
/users/dlweber/.rbenv/versions/2.4.1/bin/bundle
$  bundle --version
Bundler version 1.14.6

$  rbenv which rails
/data/src/dlss/hydra/hyrax/.internal_test_app/.bundle/bin/rails
$  rails --version
Rails 5.0.3

$  bundle exec rails c
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pry-rails'. (Bundler::GemRequireError)
Gem Load Error is: undefined method `source_index' for Gem:Module
Backtrace for gem load error is:
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:9:in `gem_installed?'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:15:in `block in command_dependencies_met?'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:14:in `each'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:14:in `all?'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/command_base_helpers.rb:14:in `command_dependencies_met?'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/command_base.rb:53:in `command'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/commands.rb:195:in `<class:Commands>'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/commands.rb:12:in `<class:Pry>'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry/commands.rb:9:in `<top (required)>'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-0.8.3/lib/pry.rb:23:in `<top (required)>'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `block in require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:259:in `load_dependency'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.0.3/lib/active_support/dependencies.rb:293:in `require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pry-rails-0.2.0/lib/pry-rails.rb:3:in `<top (required)>'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
/users/dlweber/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
```

**Comment by banister** [comment]
Thanks, looks like a breaking API change in rubygems

**Comment by rf-** [comment]
That's a super old version of Pry! Try `bundle update pry pry-rails` (along with any other pry-related gems in your Gemfile) to see if you can get up to something more recent.

Example working session:

```
Loading development environment (Rails 5.0.2)
[1] pry(main)> .ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
[4] pry(main)> Gem::VERSION
=> "2.6.11"
[5] pry(main)> Pry::VERSION
=> "0.10.4"
```
